version: 2
updates:
  - package-ecosystem: "unity"
    directory: "/"
    schedule:
      interval: "daily" # You can change this to fit your update frequency
    open-pull-requests-limit: 10
    target-branch: "main"
    commit-message:
      prefix: "chore(deps): update"
    labels:
      - "dependencies"
